// 生成的文件

// clang-format off
const char *g_block_modifier_shader_template_0 =
"#version 450\n"
"\n"
"layout (local_size_x = 4, local_size_y = 4, local_size_z = 4) in;\n"
"\n"
"layout (set = 0, binding = 0, std430) restrict readonly buffer Params {\n"
"	vec3 origin_in_voxels;\n"
"	float voxel_size;\n"
"	ivec3 block_size;\n"
"	int buffer_offset;\n"
"} u_params;\n"
"\n"
"// SDF 就地修改\n"
"layout (set = 0, binding = 1, std430) restrict buffer InSDBuffer {\n"
"	float values[];\n"
"} u_inout_sd;\n"
"\n"
"// 所有修改器共用的参数。\n"
"// 与其他着色器类型保持相同的绑定号，以简化 C++ 中的使用\n"
"layout (set = 0, binding = 4, std430) restrict readonly buffer BaseModifierParams {\n"
"	mat4 world_to_model;\n"
"	int operation;\n"
"	float smoothness;\n"
"	float sd_scale;\n"
"} u_base_modifier_params;\n"
"\n";
// clang-format on

// clang-format off
const char *g_block_modifier_shader_template_1 =
"\n"
"float sd_smooth_union(float a, float b, float s) {\n"
"	const float h = clamp(0.5 + 0.5 * (b - a) / s, 0.0, 1.0);\n"
"	return mix(b, a, h) - s * h * (1.0 - h);\n"
"}\n"
"\n"
"// 交换 a 和 b，因为它是从 SDF b 中减去 SDF a\n"
"float sd_smooth_subtract(float b, float a, float s) {\n"
"	const float h = clamp(0.5 - 0.5 * (b + a) / s, 0.0, 1.0);\n"
"	return mix(b, -a, h) + s * h * (1.0 - h);\n"
"}\n"
"\n"
"int get_zxy_index(ivec3 pos, ivec3 size) {\n"
"	return pos.y + size.y * (pos.x + size.x * pos.z);\n"
"}\n"
"\n"
"void main() {\n"
"	const ivec3 rpos = ivec3(gl_GlobalInvocationID.xyz);\n"
"\n"
"	// 输出缓冲区可能没有与工作组大小成倍数的 3D 尺寸。\n"
"	// 一些并行执行将不会做任何事。\n"
"	if (rpos.x >= u_params.block_size.x || rpos.y >= u_params.block_size.y || rpos.z >= u_params.block_size.z) {\n"
"		return;\n"
"	}\n"
"\n"
"	vec3 pos = u_params.origin_in_voxels + vec3(rpos) * u_params.voxel_size;\n"
"\n"
"	pos = (u_base_modifier_params.world_to_model * vec4(pos, 1.0)).xyz;\n"
"\n"
"	const int index = get_zxy_index(rpos, u_params.block_size) + u_params.buffer_offset;\n"
"\n"
"	float sd = u_inout_sd.values[index];\n"
"\n"
"	const float msd = get_sd(pos) * u_base_modifier_params.sd_scale;\n"
"\n"
"	if (u_base_modifier_params.operation == 0) {\n"
"		sd = sd_smooth_union(sd, msd, u_base_modifier_params.smoothness);\n"
"\n"
"	} else if (u_base_modifier_params.operation == 1) {\n"
"		sd = sd_smooth_subtract(sd, msd, u_base_modifier_params.smoothness);\n"
"\n"
"	} else {\n"
"		sd = msd;\n"
"	}\n"
"\n"
"	u_inout_sd.values[index] = sd;\n"
"}\n";
// clang-format on
