// 生成的文件

// clang-format off
const char *g_transvoxel_minimal_shader =
"shader_type spatial;\n"
"\n"
"// 来自 Voxel Tools API\n"
"uniform int u_transition_mask;\n"
"\n"
"float get_transvoxel_secondary_factor(int idata) {\n"
"	int transition_mask = u_transition_mask & 0xff;\n"
"\n"
"	int cell_border_mask = idata & 63; // 单元格接触的边\n"
"	int vertex_border_mask = (idata >> 8) & 63; // 顶点接触的边\n"
"	// 如果顶点靠近存在低分辨率邻居的边，\n"
"	// 将其移动到次位置\n"
"	int m = transition_mask & cell_border_mask;\n"
"	float t = float(m != 0);\n"
"	// 如果顶点位于一条或多条边上，且至少有一条边没有低分辨率邻居，\n"
"	// 则不移动顶点。\n"
"	t *= float((vertex_border_mask & ~transition_mask) == 0);\n"
"	\n"
"	// 调试\n"
"	//t *= 0.5 + 0.5 * sin(TIME * 4.0);\n"
"	//t *= 2.0;\n"
"\n"
"	return t;\n"
"}\n"
"\n"
"vec3 get_transvoxel_position(vec3 vertex_pos, vec4 fdata) {\n"
"	int idata = floatBitsToInt(fdata.a);\n"
"\n"
"	// 移动顶点以实现平滑过渡\n"
"	float secondary_factor = get_transvoxel_secondary_factor(idata);\n"
"	vec3 secondary_position = fdata.xyz;\n"
"	vec3 pos = mix(vertex_pos, secondary_position, secondary_factor);\n"
"\n"
"	// 如果网格合并了过渡且顶点属于某个过渡，\n"
"	// 当该过渡未激活时，我们改变顶点的位置，使\n"
"	// 所有三角形退化且不可见。\n"
"	// 这是单独渲染它们的替代方案，\n"
"	// 可减少绘制调用，也减少需要在 Godot 中创建的网格资源。\n"
"	// 理想情况下，我会像 LOD 那样调整索引缓冲区，但 Godot 并未\n"
"	// 提供任何以这种方式使用它的接口。\n"
"	int itransition = (idata >> 16) & 0xff; // 顶点是否在过渡网格上？\n"
"	float transition_cull = float(itransition == 0 || (itransition & u_transition_mask) != 0);\n"
"	pos *= transition_cull;\n"
"\n"
"	return pos;\n"
"}\n"
"\n"
"void vertex() {\n"
"	VERTEX = get_transvoxel_position(VERTEX, CUSTOM0);\n"
"}\n";
// clang-format on
